version: '3.7'

services:
  lifi-daemon:
    image: lifi-daemon:latest
    networks:
      - internal-net
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '2g'
    ports:
      - 50000:50000
    secrets:
      - api-config
    volumes:
      - "./config:/usr/src/config:ro"
    restart: always
  
networks:
  internal-net:
    driver: bridge

secrets:
  api-config:
    file: ./secrets/test.json
